#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="xuhuihuanbao_2013")]
	public partial class SyncObjectsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertsync_sewage(sync_sewage instance);
    partial void Updatesync_sewage(sync_sewage instance);
    partial void Deletesync_sewage(sync_sewage instance);
    partial void Insertsync_xxgk(sync_xxgk instance);
    partial void Updatesync_xxgk(sync_xxgk instance);
    partial void Deletesync_xxgk(sync_xxgk instance);
    partial void Insertsync_wair(sync_wair instance);
    partial void Updatesync_wair(sync_wair instance);
    partial void Deletesync_wair(sync_wair instance);
    partial void Insertsync_wwater(sync_wwater instance);
    partial void Updatesync_wwater(sync_wwater instance);
    partial void Deletesync_wwater(sync_wwater instance);
    #endregion
		
		public SyncObjectsDataContext() : 
				base(global::SyncService.Properties.Settings.Default.xuhuihuanbao_2013ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SyncObjectsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SyncObjectsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SyncObjectsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SyncObjectsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sync_sewage> sync_sewage
		{
			get
			{
				return this.GetTable<sync_sewage>();
			}
		}
		
		public System.Data.Linq.Table<sync_xxgk> sync_xxgk
		{
			get
			{
				return this.GetTable<sync_xxgk>();
			}
		}
		
		public System.Data.Linq.Table<sync_wair> sync_wair
		{
			get
			{
				return this.GetTable<sync_wair>();
			}
		}
		
		public System.Data.Linq.Table<sync_wwater> sync_wwater
		{
			get
			{
				return this.GetTable<sync_wwater>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sync_sewage")]
	public partial class sync_sewage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private System.Nullable<int> _id;
		
		private string _entName;
		
		private string _portName;
		
		private System.Nullable<System.DateTime> _monitorTime;
		
		private System.Nullable<decimal> _flow;
		
		private string _factorName;
		
		private System.Nullable<decimal> _factorValue;
		
		private string _standard;
		
		private string _district;
		
		private string _enterName;
		
		private string _entType;
		
		private string _manageType;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnidChanging(System.Nullable<int> value);
    partial void OnidChanged();
    partial void OnentNameChanging(string value);
    partial void OnentNameChanged();
    partial void OnportNameChanging(string value);
    partial void OnportNameChanged();
    partial void OnmonitorTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmonitorTimeChanged();
    partial void OnflowChanging(System.Nullable<decimal> value);
    partial void OnflowChanged();
    partial void OnfactorNameChanging(string value);
    partial void OnfactorNameChanged();
    partial void OnfactorValueChanging(System.Nullable<decimal> value);
    partial void OnfactorValueChanged();
    partial void OnstandardChanging(string value);
    partial void OnstandardChanged();
    partial void OndistrictChanging(string value);
    partial void OndistrictChanged();
    partial void OnenterNameChanging(string value);
    partial void OnenterNameChanged();
    partial void OnentTypeChanging(string value);
    partial void OnentTypeChanged();
    partial void OnmanageTypeChanging(string value);
    partial void OnmanageTypeChanged();
    #endregion
		
		public sync_sewage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entName", DbType="NVarChar(200)")]
		public string entName
		{
			get
			{
				return this._entName;
			}
			set
			{
				if ((this._entName != value))
				{
					this.OnentNameChanging(value);
					this.SendPropertyChanging();
					this._entName = value;
					this.SendPropertyChanged("entName");
					this.OnentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portName", DbType="NVarChar(200)")]
		public string portName
		{
			get
			{
				return this._portName;
			}
			set
			{
				if ((this._portName != value))
				{
					this.OnportNameChanging(value);
					this.SendPropertyChanging();
					this._portName = value;
					this.SendPropertyChanged("portName");
					this.OnportNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monitorTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> monitorTime
		{
			get
			{
				return this._monitorTime;
			}
			set
			{
				if ((this._monitorTime != value))
				{
					this.OnmonitorTimeChanging(value);
					this.SendPropertyChanging();
					this._monitorTime = value;
					this.SendPropertyChanged("monitorTime");
					this.OnmonitorTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> flow
		{
			get
			{
				return this._flow;
			}
			set
			{
				if ((this._flow != value))
				{
					this.OnflowChanging(value);
					this.SendPropertyChanging();
					this._flow = value;
					this.SendPropertyChanged("flow");
					this.OnflowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorName", DbType="NVarChar(20)")]
		public string factorName
		{
			get
			{
				return this._factorName;
			}
			set
			{
				if ((this._factorName != value))
				{
					this.OnfactorNameChanging(value);
					this.SendPropertyChanging();
					this._factorName = value;
					this.SendPropertyChanged("factorName");
					this.OnfactorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorValue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> factorValue
		{
			get
			{
				return this._factorValue;
			}
			set
			{
				if ((this._factorValue != value))
				{
					this.OnfactorValueChanging(value);
					this.SendPropertyChanging();
					this._factorValue = value;
					this.SendPropertyChanged("factorValue");
					this.OnfactorValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standard", DbType="NVarChar(50)")]
		public string standard
		{
			get
			{
				return this._standard;
			}
			set
			{
				if ((this._standard != value))
				{
					this.OnstandardChanging(value);
					this.SendPropertyChanging();
					this._standard = value;
					this.SendPropertyChanged("standard");
					this.OnstandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="NVarChar(500)")]
		public string district
		{
			get
			{
				return this._district;
			}
			set
			{
				if ((this._district != value))
				{
					this.OndistrictChanging(value);
					this.SendPropertyChanging();
					this._district = value;
					this.SendPropertyChanged("district");
					this.OndistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enterName", DbType="NVarChar(500)")]
		public string enterName
		{
			get
			{
				return this._enterName;
			}
			set
			{
				if ((this._enterName != value))
				{
					this.OnenterNameChanging(value);
					this.SendPropertyChanging();
					this._enterName = value;
					this.SendPropertyChanged("enterName");
					this.OnenterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entType", DbType="NVarChar(500)")]
		public string entType
		{
			get
			{
				return this._entType;
			}
			set
			{
				if ((this._entType != value))
				{
					this.OnentTypeChanging(value);
					this.SendPropertyChanging();
					this._entType = value;
					this.SendPropertyChanged("entType");
					this.OnentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manageType", DbType="NVarChar(500)")]
		public string manageType
		{
			get
			{
				return this._manageType;
			}
			set
			{
				if ((this._manageType != value))
				{
					this.OnmanageTypeChanging(value);
					this.SendPropertyChanging();
					this._manageType = value;
					this.SendPropertyChanged("manageType");
					this.OnmanageTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sync_xxgk")]
	public partial class sync_xxgk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _WF_SYSID;
		
		private string _WF_CASEID;
		
		private string _APPLYITEM;
		
		private string _GONGSHITYPE;
		
		private System.Nullable<System.DateTime> _GONGSHIBEGINDATE;
		
		private System.Nullable<System.DateTime> _GONGSHIENDDATE;
		
		private string _ITEMNO;
		
		private string _SUBJECT;
		
		private string _ADDRESS;
		
		private string _BUILDERUNIT;
		
		private string _HPUNIT;
		
		private string _HPCHECKACCEPTUNIT;
		
		private System.Nullable<System.DateTime> _COMPOSEDATE;
		
		private string _PIWENNAME;
		
		private string _PIWNENO;
		
		private System.Nullable<System.DateTime> _PIWENDATE;
		
		private string _SHENPIJD;
		
		private string _APPROVTYPE;
		
		private string _YUANYIN;
		
		private string _CANYUQINGKUANG;
		
		private string _ATTACH_1;
		
		private string _ATTACH_2;
		
		private string _ATTACH_3;
		
		private string _ATTACH_4;
		
		private string _PRJPROFILE;
		
		private string _PRJCS;
		
		private string _ATTACH_5;
		
		private string _APPROVEUNIT;
		
		private string _PRJCN;
		
		private System.Nullable<System.DateTime> _OPETIME;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWF_SYSIDChanging(string value);
    partial void OnWF_SYSIDChanged();
    partial void OnWF_CASEIDChanging(string value);
    partial void OnWF_CASEIDChanged();
    partial void OnAPPLYITEMChanging(string value);
    partial void OnAPPLYITEMChanged();
    partial void OnGONGSHITYPEChanging(string value);
    partial void OnGONGSHITYPEChanged();
    partial void OnGONGSHIBEGINDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGONGSHIBEGINDATEChanged();
    partial void OnGONGSHIENDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGONGSHIENDDATEChanged();
    partial void OnITEMNOChanging(string value);
    partial void OnITEMNOChanged();
    partial void OnSUBJECTChanging(string value);
    partial void OnSUBJECTChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnBUILDERUNITChanging(string value);
    partial void OnBUILDERUNITChanged();
    partial void OnHPUNITChanging(string value);
    partial void OnHPUNITChanged();
    partial void OnHPCHECKACCEPTUNITChanging(string value);
    partial void OnHPCHECKACCEPTUNITChanged();
    partial void OnCOMPOSEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCOMPOSEDATEChanged();
    partial void OnPIWENNAMEChanging(string value);
    partial void OnPIWENNAMEChanged();
    partial void OnPIWNENOChanging(string value);
    partial void OnPIWNENOChanged();
    partial void OnPIWENDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPIWENDATEChanged();
    partial void OnSHENPIJDChanging(string value);
    partial void OnSHENPIJDChanged();
    partial void OnAPPROVTYPEChanging(string value);
    partial void OnAPPROVTYPEChanged();
    partial void OnYUANYINChanging(string value);
    partial void OnYUANYINChanged();
    partial void OnCANYUQINGKUANGChanging(string value);
    partial void OnCANYUQINGKUANGChanged();
    partial void OnATTACH_1Changing(string value);
    partial void OnATTACH_1Changed();
    partial void OnATTACH_2Changing(string value);
    partial void OnATTACH_2Changed();
    partial void OnATTACH_3Changing(string value);
    partial void OnATTACH_3Changed();
    partial void OnATTACH_4Changing(string value);
    partial void OnATTACH_4Changed();
    partial void OnPRJPROFILEChanging(string value);
    partial void OnPRJPROFILEChanged();
    partial void OnPRJCSChanging(string value);
    partial void OnPRJCSChanged();
    partial void OnATTACH_5Changing(string value);
    partial void OnATTACH_5Changed();
    partial void OnAPPROVEUNITChanging(string value);
    partial void OnAPPROVEUNITChanged();
    partial void OnPRJCNChanging(string value);
    partial void OnPRJCNChanged();
    partial void OnOPETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnOPETIMEChanged();
    #endregion
		
		public sync_xxgk()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WF_SYSID", DbType="VarChar(32)")]
		public string WF_SYSID
		{
			get
			{
				return this._WF_SYSID;
			}
			set
			{
				if ((this._WF_SYSID != value))
				{
					this.OnWF_SYSIDChanging(value);
					this.SendPropertyChanging();
					this._WF_SYSID = value;
					this.SendPropertyChanged("WF_SYSID");
					this.OnWF_SYSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WF_CASEID", DbType="VarChar(32)")]
		public string WF_CASEID
		{
			get
			{
				return this._WF_CASEID;
			}
			set
			{
				if ((this._WF_CASEID != value))
				{
					this.OnWF_CASEIDChanging(value);
					this.SendPropertyChanging();
					this._WF_CASEID = value;
					this.SendPropertyChanged("WF_CASEID");
					this.OnWF_CASEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLYITEM", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string APPLYITEM
		{
			get
			{
				return this._APPLYITEM;
			}
			set
			{
				if ((this._APPLYITEM != value))
				{
					this.OnAPPLYITEMChanging(value);
					this.SendPropertyChanging();
					this._APPLYITEM = value;
					this.SendPropertyChanged("APPLYITEM");
					this.OnAPPLYITEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGSHITYPE", DbType="VarChar(50)")]
		public string GONGSHITYPE
		{
			get
			{
				return this._GONGSHITYPE;
			}
			set
			{
				if ((this._GONGSHITYPE != value))
				{
					this.OnGONGSHITYPEChanging(value);
					this.SendPropertyChanging();
					this._GONGSHITYPE = value;
					this.SendPropertyChanged("GONGSHITYPE");
					this.OnGONGSHITYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGSHIBEGINDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GONGSHIBEGINDATE
		{
			get
			{
				return this._GONGSHIBEGINDATE;
			}
			set
			{
				if ((this._GONGSHIBEGINDATE != value))
				{
					this.OnGONGSHIBEGINDATEChanging(value);
					this.SendPropertyChanging();
					this._GONGSHIBEGINDATE = value;
					this.SendPropertyChanged("GONGSHIBEGINDATE");
					this.OnGONGSHIBEGINDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGSHIENDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GONGSHIENDDATE
		{
			get
			{
				return this._GONGSHIENDDATE;
			}
			set
			{
				if ((this._GONGSHIENDDATE != value))
				{
					this.OnGONGSHIENDDATEChanging(value);
					this.SendPropertyChanging();
					this._GONGSHIENDDATE = value;
					this.SendPropertyChanged("GONGSHIENDDATE");
					this.OnGONGSHIENDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNO", DbType="VarChar(100)")]
		public string ITEMNO
		{
			get
			{
				return this._ITEMNO;
			}
			set
			{
				if ((this._ITEMNO != value))
				{
					this.OnITEMNOChanging(value);
					this.SendPropertyChanging();
					this._ITEMNO = value;
					this.SendPropertyChanged("ITEMNO");
					this.OnITEMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECT", DbType="VarChar(500)")]
		public string SUBJECT
		{
			get
			{
				return this._SUBJECT;
			}
			set
			{
				if ((this._SUBJECT != value))
				{
					this.OnSUBJECTChanging(value);
					this.SendPropertyChanging();
					this._SUBJECT = value;
					this.SendPropertyChanged("SUBJECT");
					this.OnSUBJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(500)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDERUNIT", DbType="VarChar(500)")]
		public string BUILDERUNIT
		{
			get
			{
				return this._BUILDERUNIT;
			}
			set
			{
				if ((this._BUILDERUNIT != value))
				{
					this.OnBUILDERUNITChanging(value);
					this.SendPropertyChanging();
					this._BUILDERUNIT = value;
					this.SendPropertyChanged("BUILDERUNIT");
					this.OnBUILDERUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HPUNIT", DbType="VarChar(500)")]
		public string HPUNIT
		{
			get
			{
				return this._HPUNIT;
			}
			set
			{
				if ((this._HPUNIT != value))
				{
					this.OnHPUNITChanging(value);
					this.SendPropertyChanging();
					this._HPUNIT = value;
					this.SendPropertyChanged("HPUNIT");
					this.OnHPUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HPCHECKACCEPTUNIT", DbType="VarChar(500)")]
		public string HPCHECKACCEPTUNIT
		{
			get
			{
				return this._HPCHECKACCEPTUNIT;
			}
			set
			{
				if ((this._HPCHECKACCEPTUNIT != value))
				{
					this.OnHPCHECKACCEPTUNITChanging(value);
					this.SendPropertyChanging();
					this._HPCHECKACCEPTUNIT = value;
					this.SendPropertyChanged("HPCHECKACCEPTUNIT");
					this.OnHPCHECKACCEPTUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPOSEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> COMPOSEDATE
		{
			get
			{
				return this._COMPOSEDATE;
			}
			set
			{
				if ((this._COMPOSEDATE != value))
				{
					this.OnCOMPOSEDATEChanging(value);
					this.SendPropertyChanging();
					this._COMPOSEDATE = value;
					this.SendPropertyChanged("COMPOSEDATE");
					this.OnCOMPOSEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIWENNAME", DbType="VarChar(100)")]
		public string PIWENNAME
		{
			get
			{
				return this._PIWENNAME;
			}
			set
			{
				if ((this._PIWENNAME != value))
				{
					this.OnPIWENNAMEChanging(value);
					this.SendPropertyChanging();
					this._PIWENNAME = value;
					this.SendPropertyChanged("PIWENNAME");
					this.OnPIWENNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIWNENO", DbType="VarChar(100)")]
		public string PIWNENO
		{
			get
			{
				return this._PIWNENO;
			}
			set
			{
				if ((this._PIWNENO != value))
				{
					this.OnPIWNENOChanging(value);
					this.SendPropertyChanging();
					this._PIWNENO = value;
					this.SendPropertyChanged("PIWNENO");
					this.OnPIWNENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIWENDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PIWENDATE
		{
			get
			{
				return this._PIWENDATE;
			}
			set
			{
				if ((this._PIWENDATE != value))
				{
					this.OnPIWENDATEChanging(value);
					this.SendPropertyChanging();
					this._PIWENDATE = value;
					this.SendPropertyChanged("PIWENDATE");
					this.OnPIWENDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHENPIJD", DbType="VarChar(50)")]
		public string SHENPIJD
		{
			get
			{
				return this._SHENPIJD;
			}
			set
			{
				if ((this._SHENPIJD != value))
				{
					this.OnSHENPIJDChanging(value);
					this.SendPropertyChanging();
					this._SHENPIJD = value;
					this.SendPropertyChanged("SHENPIJD");
					this.OnSHENPIJDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVTYPE", DbType="VarChar(50)")]
		public string APPROVTYPE
		{
			get
			{
				return this._APPROVTYPE;
			}
			set
			{
				if ((this._APPROVTYPE != value))
				{
					this.OnAPPROVTYPEChanging(value);
					this.SendPropertyChanging();
					this._APPROVTYPE = value;
					this.SendPropertyChanged("APPROVTYPE");
					this.OnAPPROVTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YUANYIN", DbType="VarChar(2000)")]
		public string YUANYIN
		{
			get
			{
				return this._YUANYIN;
			}
			set
			{
				if ((this._YUANYIN != value))
				{
					this.OnYUANYINChanging(value);
					this.SendPropertyChanging();
					this._YUANYIN = value;
					this.SendPropertyChanged("YUANYIN");
					this.OnYUANYINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANYUQINGKUANG", DbType="VarChar(2000)")]
		public string CANYUQINGKUANG
		{
			get
			{
				return this._CANYUQINGKUANG;
			}
			set
			{
				if ((this._CANYUQINGKUANG != value))
				{
					this.OnCANYUQINGKUANGChanging(value);
					this.SendPropertyChanging();
					this._CANYUQINGKUANG = value;
					this.SendPropertyChanged("CANYUQINGKUANG");
					this.OnCANYUQINGKUANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACH_1", DbType="VarChar(300)")]
		public string ATTACH_1
		{
			get
			{
				return this._ATTACH_1;
			}
			set
			{
				if ((this._ATTACH_1 != value))
				{
					this.OnATTACH_1Changing(value);
					this.SendPropertyChanging();
					this._ATTACH_1 = value;
					this.SendPropertyChanged("ATTACH_1");
					this.OnATTACH_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACH_2", DbType="VarChar(500)")]
		public string ATTACH_2
		{
			get
			{
				return this._ATTACH_2;
			}
			set
			{
				if ((this._ATTACH_2 != value))
				{
					this.OnATTACH_2Changing(value);
					this.SendPropertyChanging();
					this._ATTACH_2 = value;
					this.SendPropertyChanged("ATTACH_2");
					this.OnATTACH_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACH_3", DbType="VarChar(500)")]
		public string ATTACH_3
		{
			get
			{
				return this._ATTACH_3;
			}
			set
			{
				if ((this._ATTACH_3 != value))
				{
					this.OnATTACH_3Changing(value);
					this.SendPropertyChanging();
					this._ATTACH_3 = value;
					this.SendPropertyChanged("ATTACH_3");
					this.OnATTACH_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACH_4", DbType="VarChar(500)")]
		public string ATTACH_4
		{
			get
			{
				return this._ATTACH_4;
			}
			set
			{
				if ((this._ATTACH_4 != value))
				{
					this.OnATTACH_4Changing(value);
					this.SendPropertyChanging();
					this._ATTACH_4 = value;
					this.SendPropertyChanged("ATTACH_4");
					this.OnATTACH_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRJPROFILE", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PRJPROFILE
		{
			get
			{
				return this._PRJPROFILE;
			}
			set
			{
				if ((this._PRJPROFILE != value))
				{
					this.OnPRJPROFILEChanging(value);
					this.SendPropertyChanging();
					this._PRJPROFILE = value;
					this.SendPropertyChanged("PRJPROFILE");
					this.OnPRJPROFILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRJCS", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PRJCS
		{
			get
			{
				return this._PRJCS;
			}
			set
			{
				if ((this._PRJCS != value))
				{
					this.OnPRJCSChanging(value);
					this.SendPropertyChanging();
					this._PRJCS = value;
					this.SendPropertyChanged("PRJCS");
					this.OnPRJCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACH_5", DbType="VarChar(500)")]
		public string ATTACH_5
		{
			get
			{
				return this._ATTACH_5;
			}
			set
			{
				if ((this._ATTACH_5 != value))
				{
					this.OnATTACH_5Changing(value);
					this.SendPropertyChanging();
					this._ATTACH_5 = value;
					this.SendPropertyChanged("ATTACH_5");
					this.OnATTACH_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVEUNIT", DbType="VarChar(50)")]
		public string APPROVEUNIT
		{
			get
			{
				return this._APPROVEUNIT;
			}
			set
			{
				if ((this._APPROVEUNIT != value))
				{
					this.OnAPPROVEUNITChanging(value);
					this.SendPropertyChanging();
					this._APPROVEUNIT = value;
					this.SendPropertyChanged("APPROVEUNIT");
					this.OnAPPROVEUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRJCN", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PRJCN
		{
			get
			{
				return this._PRJCN;
			}
			set
			{
				if ((this._PRJCN != value))
				{
					this.OnPRJCNChanging(value);
					this.SendPropertyChanging();
					this._PRJCN = value;
					this.SendPropertyChanged("PRJCN");
					this.OnPRJCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> OPETIME
		{
			get
			{
				return this._OPETIME;
			}
			set
			{
				if ((this._OPETIME != value))
				{
					this.OnOPETIMEChanging(value);
					this.SendPropertyChanging();
					this._OPETIME = value;
					this.SendPropertyChanged("OPETIME");
					this.OnOPETIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sync_wair")]
	public partial class sync_wair : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private System.Nullable<int> _id;
		
		private string _entName;
		
		private string _portName;
		
		private System.Nullable<System.DateTime> _monitorTime;
		
		private System.Nullable<decimal> _flow;
		
		private string _factorName;
		
		private System.Nullable<decimal> _factorValue;
		
		private string _standard;
		
		private string _district;
		
		private string _enterName;
		
		private string _entType;
		
		private string _manageType;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnidChanging(System.Nullable<int> value);
    partial void OnidChanged();
    partial void OnentNameChanging(string value);
    partial void OnentNameChanged();
    partial void OnportNameChanging(string value);
    partial void OnportNameChanged();
    partial void OnmonitorTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmonitorTimeChanged();
    partial void OnflowChanging(System.Nullable<decimal> value);
    partial void OnflowChanged();
    partial void OnfactorNameChanging(string value);
    partial void OnfactorNameChanged();
    partial void OnfactorValueChanging(System.Nullable<decimal> value);
    partial void OnfactorValueChanged();
    partial void OnstandardChanging(string value);
    partial void OnstandardChanged();
    partial void OndistrictChanging(string value);
    partial void OndistrictChanged();
    partial void OnenterNameChanging(string value);
    partial void OnenterNameChanged();
    partial void OnentTypeChanging(string value);
    partial void OnentTypeChanged();
    partial void OnmanageTypeChanging(string value);
    partial void OnmanageTypeChanged();
    #endregion
		
		public sync_wair()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entName", DbType="NVarChar(200)")]
		public string entName
		{
			get
			{
				return this._entName;
			}
			set
			{
				if ((this._entName != value))
				{
					this.OnentNameChanging(value);
					this.SendPropertyChanging();
					this._entName = value;
					this.SendPropertyChanged("entName");
					this.OnentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portName", DbType="NVarChar(200)")]
		public string portName
		{
			get
			{
				return this._portName;
			}
			set
			{
				if ((this._portName != value))
				{
					this.OnportNameChanging(value);
					this.SendPropertyChanging();
					this._portName = value;
					this.SendPropertyChanged("portName");
					this.OnportNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monitorTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> monitorTime
		{
			get
			{
				return this._monitorTime;
			}
			set
			{
				if ((this._monitorTime != value))
				{
					this.OnmonitorTimeChanging(value);
					this.SendPropertyChanging();
					this._monitorTime = value;
					this.SendPropertyChanged("monitorTime");
					this.OnmonitorTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> flow
		{
			get
			{
				return this._flow;
			}
			set
			{
				if ((this._flow != value))
				{
					this.OnflowChanging(value);
					this.SendPropertyChanging();
					this._flow = value;
					this.SendPropertyChanged("flow");
					this.OnflowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorName", DbType="NVarChar(20)")]
		public string factorName
		{
			get
			{
				return this._factorName;
			}
			set
			{
				if ((this._factorName != value))
				{
					this.OnfactorNameChanging(value);
					this.SendPropertyChanging();
					this._factorName = value;
					this.SendPropertyChanged("factorName");
					this.OnfactorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorValue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> factorValue
		{
			get
			{
				return this._factorValue;
			}
			set
			{
				if ((this._factorValue != value))
				{
					this.OnfactorValueChanging(value);
					this.SendPropertyChanging();
					this._factorValue = value;
					this.SendPropertyChanged("factorValue");
					this.OnfactorValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standard", DbType="NVarChar(50)")]
		public string standard
		{
			get
			{
				return this._standard;
			}
			set
			{
				if ((this._standard != value))
				{
					this.OnstandardChanging(value);
					this.SendPropertyChanging();
					this._standard = value;
					this.SendPropertyChanged("standard");
					this.OnstandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="NVarChar(500)")]
		public string district
		{
			get
			{
				return this._district;
			}
			set
			{
				if ((this._district != value))
				{
					this.OndistrictChanging(value);
					this.SendPropertyChanging();
					this._district = value;
					this.SendPropertyChanged("district");
					this.OndistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enterName", DbType="NVarChar(500)")]
		public string enterName
		{
			get
			{
				return this._enterName;
			}
			set
			{
				if ((this._enterName != value))
				{
					this.OnenterNameChanging(value);
					this.SendPropertyChanging();
					this._enterName = value;
					this.SendPropertyChanged("enterName");
					this.OnenterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entType", DbType="NVarChar(500)")]
		public string entType
		{
			get
			{
				return this._entType;
			}
			set
			{
				if ((this._entType != value))
				{
					this.OnentTypeChanging(value);
					this.SendPropertyChanging();
					this._entType = value;
					this.SendPropertyChanged("entType");
					this.OnentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manageType", DbType="NVarChar(500)")]
		public string manageType
		{
			get
			{
				return this._manageType;
			}
			set
			{
				if ((this._manageType != value))
				{
					this.OnmanageTypeChanging(value);
					this.SendPropertyChanging();
					this._manageType = value;
					this.SendPropertyChanged("manageType");
					this.OnmanageTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sync_wwater")]
	public partial class sync_wwater : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private System.Nullable<int> _id;
		
		private string _entName;
		
		private string _portName;
		
		private System.Nullable<System.DateTime> _monitorTime;
		
		private System.Nullable<decimal> _flow;
		
		private string _factorName;
		
		private System.Nullable<decimal> _factorValue;
		
		private string _standard;
		
		private string _district;
		
		private string _enterName;
		
		private string _entType;
		
		private string _manageType;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnidChanging(System.Nullable<int> value);
    partial void OnidChanged();
    partial void OnentNameChanging(string value);
    partial void OnentNameChanged();
    partial void OnportNameChanging(string value);
    partial void OnportNameChanged();
    partial void OnmonitorTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmonitorTimeChanged();
    partial void OnflowChanging(System.Nullable<decimal> value);
    partial void OnflowChanged();
    partial void OnfactorNameChanging(string value);
    partial void OnfactorNameChanged();
    partial void OnfactorValueChanging(System.Nullable<decimal> value);
    partial void OnfactorValueChanged();
    partial void OnstandardChanging(string value);
    partial void OnstandardChanged();
    partial void OndistrictChanging(string value);
    partial void OndistrictChanged();
    partial void OnenterNameChanging(string value);
    partial void OnenterNameChanged();
    partial void OnentTypeChanging(string value);
    partial void OnentTypeChanged();
    partial void OnmanageTypeChanging(string value);
    partial void OnmanageTypeChanged();
    #endregion
		
		public sync_wwater()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entName", DbType="NVarChar(200)")]
		public string entName
		{
			get
			{
				return this._entName;
			}
			set
			{
				if ((this._entName != value))
				{
					this.OnentNameChanging(value);
					this.SendPropertyChanging();
					this._entName = value;
					this.SendPropertyChanged("entName");
					this.OnentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portName", DbType="NVarChar(200)")]
		public string portName
		{
			get
			{
				return this._portName;
			}
			set
			{
				if ((this._portName != value))
				{
					this.OnportNameChanging(value);
					this.SendPropertyChanging();
					this._portName = value;
					this.SendPropertyChanged("portName");
					this.OnportNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monitorTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> monitorTime
		{
			get
			{
				return this._monitorTime;
			}
			set
			{
				if ((this._monitorTime != value))
				{
					this.OnmonitorTimeChanging(value);
					this.SendPropertyChanging();
					this._monitorTime = value;
					this.SendPropertyChanged("monitorTime");
					this.OnmonitorTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> flow
		{
			get
			{
				return this._flow;
			}
			set
			{
				if ((this._flow != value))
				{
					this.OnflowChanging(value);
					this.SendPropertyChanging();
					this._flow = value;
					this.SendPropertyChanged("flow");
					this.OnflowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorName", DbType="NVarChar(20)")]
		public string factorName
		{
			get
			{
				return this._factorName;
			}
			set
			{
				if ((this._factorName != value))
				{
					this.OnfactorNameChanging(value);
					this.SendPropertyChanging();
					this._factorName = value;
					this.SendPropertyChanged("factorName");
					this.OnfactorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorValue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> factorValue
		{
			get
			{
				return this._factorValue;
			}
			set
			{
				if ((this._factorValue != value))
				{
					this.OnfactorValueChanging(value);
					this.SendPropertyChanging();
					this._factorValue = value;
					this.SendPropertyChanged("factorValue");
					this.OnfactorValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standard", DbType="NVarChar(50)")]
		public string standard
		{
			get
			{
				return this._standard;
			}
			set
			{
				if ((this._standard != value))
				{
					this.OnstandardChanging(value);
					this.SendPropertyChanging();
					this._standard = value;
					this.SendPropertyChanged("standard");
					this.OnstandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="NVarChar(500)")]
		public string district
		{
			get
			{
				return this._district;
			}
			set
			{
				if ((this._district != value))
				{
					this.OndistrictChanging(value);
					this.SendPropertyChanging();
					this._district = value;
					this.SendPropertyChanged("district");
					this.OndistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enterName", DbType="NVarChar(500)")]
		public string enterName
		{
			get
			{
				return this._enterName;
			}
			set
			{
				if ((this._enterName != value))
				{
					this.OnenterNameChanging(value);
					this.SendPropertyChanging();
					this._enterName = value;
					this.SendPropertyChanged("enterName");
					this.OnenterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entType", DbType="NVarChar(500)")]
		public string entType
		{
			get
			{
				return this._entType;
			}
			set
			{
				if ((this._entType != value))
				{
					this.OnentTypeChanging(value);
					this.SendPropertyChanging();
					this._entType = value;
					this.SendPropertyChanged("entType");
					this.OnentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manageType", DbType="NVarChar(500)")]
		public string manageType
		{
			get
			{
				return this._manageType;
			}
			set
			{
				if ((this._manageType != value))
				{
					this.OnmanageTypeChanging(value);
					this.SendPropertyChanging();
					this._manageType = value;
					this.SendPropertyChanged("manageType");
					this.OnmanageTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
